## What is Tensor?

- Tensor is a data structure used to store numbers. Can be of N-dimensions. 

- 0D tensor
    - 0D tensor is nothing but a 0D array or scaler value.
    - Example :- 5 -> 0D tensor, Rank 0

- 1D tensor
    - 1D tensor is nothing but vector or an 1D array and number of elements inside this 1D tensor determines dimension of the vector.
    - Example :- [1,2,3] -> 1D tensor and 3D vector, Rank 1

- 2D tensor 
    - 2D tensor is nothing but collection of 1D tensor also knows as matrix.
    - Example :- [[1,2,3], [4,5,6]] -> 2D tensor or matrix, Rank 2

- 3D tensor
    - 3D tensor is collection of 2D tensor.
    - Example :- In the domain of NLP when a collection of sentence is represented using 3D tensor and one sentence is represented by matrix which shows which words are present in the sentence. 

- 4D tensor
    - 4D tensor is collection of 3D tensor.
    - Example :- In the domain of CV a collection of images are represented by 4D tensor while one image is represented in 3D tensor.

### Why are tensors useful for deep learning?
- As we show above tensor can be used to efficiently represent text, image, video and other high-dimensional data and this provides computer a mean to understand and make computation on this data thus they are very useful in deep learning because in deep leaning we are dealing with high-dimensional data. 

### Why are tensors better suited for GPU computation than Python lists?
- Tensors are suitable for GPU computation because they are homogenous, contiguously stored, optimized for parallel mathematical operation and are nicely integrated though libraries like Pytorch and Tensorflow to use multiple cores of GPU to complete computation task.

## Creating Tensor

In [1]:
import torch

print(torch.cuda.is_available())

x = torch.tensor([1, 2, 3])
x

True


tensor([1, 2, 3])

In [2]:
print(type(x))
print(x.dtype)
print(x.shape)
print(x.ndim)

<class 'torch.Tensor'>
torch.int64
torch.Size([3])
1


### What is the tensor datatype?
- As we have stored integers tensor.int64 is the datatype of this tensor.

### What shape does this tensor have?
- Shape is (3) and dimension is 1.

## Tensor Dimensions

In [3]:
scalar = torch.tensor(5)

vector = torch.tensor([1, 2, 3])

matrix = torch.tensor([
    [1, 2], 
    [3, 4]
])

### What is dimension?
- Dimension or axis is a direction along which data is arranged.

### What is shape?
- shape refers to layout or structure of tensor. It describes how many elements are present along each axis. 

### What is rank?
- No. of dimensions is called Rank.

In [4]:
print(scalar.shape)
print(vector.shape)
print(matrix.shape)

torch.Size([])
torch.Size([3])
torch.Size([2, 2])


## Tensor Initialization Methods

In [5]:
torch.zeros([2,3])

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones([3,2,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [7]:
torch.rand([3,3])

tensor([[0.2850, 0.6121, 0.1864],
        [0.1928, 0.5655, 0.6154],
        [0.6899, 0.2164, 0.1483]])

### When would random initialization be useful?
- Random initialization of tensors is primarily useful for initializing the weights of neural networks to break symmetry and ensure that neurons learn different features during training.

### Why are neural network weights not initialized to all zeros?
- If weights are initialized to the same value (such as zero or one), all neurons in a layer will compute identical outputs and receive identical gradient updates, effectively reducing the network's capacity to learn complex patterns. 

## Tensor Datatype

In [8]:
x = torch.tensor([1, 2, 3])

x.dtype

torch.int64

In [9]:
x.float()

tensor([1., 2., 3.])

### Why does deep learning usually use floating point tensors?
- Because floating point tensors provide necessary precision and range to handle the fractional values and extreme magnitudes inherent in neural network computations

### What happens if integer tensors are used during gradient computation?
- If integers are used small gradient changes would be rounded up to zero and learning will be halted.

## Basic Tensor Operations

In [10]:
x = torch.tensor([[1, 2],
                  [3, 4]])

y = torch.tensor([[5, 6], 
                  [7, 8]])

x + y

tensor([[ 6,  8],
        [10, 12]])

In [11]:
x * y

tensor([[ 5, 12],
        [21, 32]])

### Is * matrix multiplication here?
- No

### What operation is actually happening?
- multiplication of numbers which are in same position.

## Matrix Multiplication

In [12]:
x = torch.tensor([[1, 2],
                  [3, 4]])

y = torch.tensor([[5, 6], 
                  [7, 8]])

torch.matmul(x, y)

tensor([[19, 22],
        [43, 50]])

### Why is matrix multiplication fundamental in neural networks?
- Matrix multiplication is fundamental in neural networks because it provides means to perform linear transformations across layers. 

### What shape rules must hold?
- No. of columns of the first matrix should be equal to No. of rows of the second matrix for matrix multiplication. 

## Tensor Indexing

In [13]:
x = torch.tensor([
    [[1, 2],
    [3, 4]],
    
    [[5, 6],
    [7, 8]]
])

In [14]:
print(x[0])
print(x[0,1])
print(x[:, 1])

tensor([[1, 2],
        [3, 4]])
tensor([3, 4])
tensor([[3, 4],
        [7, 8]])


## Reshaping Tensors

In [15]:
x = torch.arange(6)

x.reshape((3, 2))

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### What must remain constant during reshape?
- No. of elements in a tensor must remain constant.

## CPU vs GPU

In [16]:
torch.cuda.is_available()

True

### Why are GPUs useful for deep learning?
- GPUs are useful for deep learning because their architecture is optimized for parallel processing, allowing them to perform thousands of simultaneous matrix and tensor operations that are central to neural network training. 

### Why are tensors central to GPU acceleration?
- Tensors are central to GPU acceleration because they are the primary data structure used in deep learning, representing inputs, weights, activations, and outputs as multi-dimensional arrays that map directly to parallel hardware.