## What Is a Neural Network Layer?

- A neural network layer is a learnable transformation that takes an input tensor, applies a linear transformation and usually a nonlinear activation, then produces an output tensor for the next layer. 

- A neural network layer is fundamentally a learnable mathematical transformation that:

        input → linear transformation → optional nonlinearity → output

- For a single neuron:
        y = f(wx + b)

- For an entire layer:
        Y = f(XW + b)

- In y = f(Wx + b):

        x = input (not learned)
        W = weights (learned)
        b = bias (learned)
        f = activation function (fixed choice made by the designer)

### What does a neural network layer fundamentally compute?
- It computes a learnable transformation of input data which is done using multiplying it by weight and adding bias also We add nonlinearity not because the input is complex, but because stacking only linear transformations still produces a linear transformation.
- Nonlinear activations allow the network to represent functions that cannot be expressed by a single linear model.

### Why is a neural network mostly repeated matrix multiplication + nonlinearity?
- Neural networks repeatedly apply matrix multiplication to learn weighted combinations of features and activation functions to introduce nonlinearity. Matrix multiplication alone can only represent linear transformations, while nonlinear activations allow deep networks to learn complex patterns and decision boundaries.

### Why Matrix Multiplication?
- Matrix multiplication allows all neurons in a layer to process all inputs simultaneously in a highly optimized form that GPUs can execute efficiently.

- Suppose:

        Input:
                Age
                Income
                Balance

        The network must learn:

                How important is Age?
                How important is Income?
                How important is Balance?

- Matrix multiplication is the compact way to compute weighted combinations of all inputs for many neurons simultaneously.

### Why nonlinearity?
- Suppose: 

        Layer 1:
                z₁ = W₁x + b₁

        Layer 2:
                z₂ = W₂z₁ + b₂

        Substitute:
                z₂ = W₂(W₁x + b₁) + b₂

        After simplification:
                z₂ = Ax + c

- Still a single linear transformation. This means without activation functions, multiple stacked layers collapse into one equivalent linear transformation, so increasing depth provides no additional representational power. So now computation becomes:

         Wx + b    
            ↓      
        Activation 
            ↓      
         Wx + b    
            ↓      
        Activation 

- Each layer can learn progressively more useful representations of the input data.

        Images:
        pixels → edges → shapes → objects

## Manual Linear Transformation

In [12]:
import torch

x = torch.tensor([1.0, 2.0])

W = torch.tensor([
    [0.5, 1.0],
    [1.5, -1.0]
])

b = torch.tensor([0.5, -0.5])

z = torch.matmul(W, x) + b
z

tensor([ 3., -1.])

In [13]:
W.shape
x.shape
b.shape

torch.Size([2])

- Here W represents matrix of all the weights of neuron in a layer similarly b represents vector of all the biases of neurons in a layer. 
- Now when we update them, gradient is calculated w.r.t all the weights of neurons in a layer (all the parameters) means we also update them all at once. Similarly with bias too we calculate gradient w.r.t all the biases of all the neurons in the layer and also update them all at once. 
- Shape of W and b depends on No. of inputs and outputs of the layer. 

        weight shape = (n_outputs, n_inputs)
        bias shape   = (n_outputs,) 

### What shape is: w, x and b?
- Shape of w is (2, 2), x is (2,) and b is (2,).

### Why does matrix multiplication work here?
- Because the shapes are compatible and because matrix multiplication is exactly the operation that computes the weighted sums each neuron needs.

## Why Linear Transformations Alone Are Not Enough

### What happens if a neural network uses only linear layers?
- Then neural network would not be able to capture the nonlinear nature of input data as well it would not be able to learn and fit the data that well.
- If a neural network uses only linear layers, the entire network becomes mathematically equivalent to a single linear transformation. As a result, adding more layers does not increase the model's expressive power, and the network cannot learn nonlinear relationships in the data.

### Why would multiple linear layers collapse into a single linear transformation?
- Multiple linear layers collapse into a single linear transformation because the composition of linear transformations is itself a linear transformation.

        Layer 1:
                z₁ = W₁x + b₁

        Layer 2:
                z₂ = W₂z₁ + b₂

        Substitute:
                z₂ = W₂(W₁x + b₁) + b₂

        After simplification:
                z₂ = Ax + c

- Depth becomes useful only when nonlinear activation functions are inserted between linear transformations.

## Activation Functions

In [14]:
torch.relu(z)

tensor([3., 0.])

### What does ReLU do?
- If input is negative it returns 0 as output but if input is positive then it returns that same value back.
- ReLU (Rectified Linear Unit) is an activation function defined by the formula $f(x) = \max(0, x)$, meaning it outputs the input directly if it is positive and zero otherwise.

### Why introduce nonlinearity?
- As explained above depth becomes useful only when nonlinear activation functions are inserted between linear transformations.

## Sigmoid Function

In [15]:
x = torch.tensor([-2.0, 0.0, 2.0, 3.0])

torch.sigmoid(x)

tensor([0.1192, 0.5000, 0.8808, 0.9526])

### Why does sigmoid squash outputs between 0 and 1?
- The sigmoid function maps inputs to the range (0, 1) because it is defined by the mathematical formula $ \sigma(x) = \frac{1}{1 + e^{-x}} $. This specific structure ensures that as the input approaches negative infinity, the output asymptotically approaches 0, and as the input approaches positive infinity, the output asymptotically approaches 1.

### Why is sigmoid useful for binary classification?
- The sigmoid function is essential for binary classification because it maps any real-valued input to a value strictly between 0 and 1, which can be directly interpreted as a probability.  This transformation allows models to output probabilistic scores rather than raw linear values, enabling clear decision-making.

## Tanh Activation

In [16]:
torch.tanh(x)

tensor([-0.9640,  0.0000,  0.9640,  0.9951])

### Difference between sigmoid and tanh?
- Tanh (hyperbolic tangent) is a mathematical function defined as $ tanh(x)= \frac{e^{x} - e^{-x}}{e^{x} + e^{-x}} $. Its output range is (-1, 1), and it is an odd function symmetric around the origin, meaning tanh(−x) = −tanh(x).

### Why is tanh zero-centered?
- The tanh (hyperbolic tangent) function is zero-centered because its mathematical definition maps inputs symmetrically around the origin, producing outputs in the range (-1, 1) with a mean of zero.
- Unlike the sigmoid function, which outputs only positive values between 0 and 1, tanh’s symmetry allows it to handle both positive and negative relationships, resulting in more balanced weight updates and faster convergence during neural network training.

## Activation Function Intuition

### Why are activation functions essential?
- Activation functions are essential because they introduce nonlinearity into neural networks. Without them, multiple linear layers collapse into a single linear transformation, making depth useless and preventing the network from learning complex patterns and decision boundaries.

### What kind of patterns become learnable after adding nonlinearity?
- After adding nonlinearity, a neural network can learn complex feature interactions, nonlinear relationships, curved decision boundaries, and hierarchical representations that cannot be expressed by a single linear transformation.

### Logistic Regression learns one decision boundary Deep Neural Network learns many intermediate representations before making a decision.

## Building First Neural Network Layer

In [17]:
layer = torch.nn.Linear(2, 3)
layer

Linear(in_features=2, out_features=3, bias=True)

### What do 2 and 3 represent?
- 2 represents No. of inputs given to the layer and 3 represents No. of outputs layer returns.

In [18]:
print(layer.weight)
print(layer.bias)

Parameter containing:
tensor([[-0.0832, -0.0927],
        [-0.0450,  0.0259],
        [ 0.3340, -0.4514]], requires_grad=True)
Parameter containing:
tensor([-0.2169, -0.6158, -0.2261], requires_grad=True)


### What shapes do weights and biases have?
- Weight has shape (3,2) and bias has shape (3, ) as we have seen in `Manual Linear Transformation` section.

### Why are parameters initialized randomly?
- Neural network parameters are initialized randomly to break symmetry between neurons. If all neurons started with identical weights and biases, they would produce identical outputs, receive identical gradients, and learn the same features. Random initialization ensures different neurons learn different representations while keeping values small enough for stable training.

## Forward Pass

In [19]:
x = torch.tensor([1.0, 2.0])

output = layer(x)
output

tensor([-0.4854, -0.6091, -0.7949], grad_fn=<ViewBackward0>)

- Note: When a layer is created, PyTorch automatically creates and randomly initializes the layer's weight matrix and bias vector. These are the learnable parameters that will later be updated during training.

### What operation internally occurred?
- PyTorch performed a linear transformation by computing output = Wx + b , where W is the layer's weight matrix and b is the bias vector. The resulting tensor was returned as the layer output.

### Is training happening yet?
- No. Only a forward pass is occurring. The layer uses its current weights and biases to compute an output. No loss has been calculated, no gradients have been computed, and no parameters have been updated.

## Multi-Layer Intuition

In [20]:
model = torch.nn.Sequential(
    torch.nn.Linear(2, 4),
    torch.nn.ReLU(),
    torch.nn.Linear(4, 1)
)

model(x)

tensor([-0.1518], grad_fn=<ViewBackward0>)

### What is happening layer-by-layer?
- On layer 1 linear transformation is applied on the input on of shape (2,) y = Wx + b, on layer 2 output from first layer is passed through activation function to introduce non linearity and on layer 3 output form previous layer is again linearly transformed which gives final output of this layer which is of shape (1,).

        Input          (2,)
            ↓   
        Linear(2,4)
            ↓   
        Hidden         (4,)
            ↓   
        ReLU
            ↓   
        Hidden         (4,)
            ↓   
        Linear(4,1)
            ↓   
        Output         (1,)

### Why does hidden dimension exist?
- A hidden layer provides a place where intermediate representations can be learned, while the hidden dimension determines the size of that representation. Increasing the hidden dimension gives the network more capacity to learn and store useful feature transformations, but also increases the number of parameters and the risk of overfitting.

## Parameters and Learnability

In [26]:
for name, param in model.named_parameters():
    print(name, param.shape)

0.weight torch.Size([4, 2])
0.bias torch.Size([4])
2.weight torch.Size([1, 4])
2.bias torch.Size([1])


### Which tensors are learnable?
- 0.weight, 0.bias, 2.weight, 2.bias are learnable tensor.

### Why do these require gradients?
- These tensors require gradients because they are the parameters the model learns during training. PyTorch computes the gradient of the loss with respect to each parameter so the optimizer knows how to update them to reduce the loss.